import { withBrandIntro } from './brand';
import type { FormDefinition } from './types';

export const intakeHeForm: FormDefinition = {
  slug: 'intake-he',
  title: 'שאלון היכרות לפני פגישה',
  intro: 'נשמח להכיר אתכם, את הבית ואת מטרות השיפוץ.',
  submitLabel: 'שליחה',
  successTitle: 'הפרטים התקבלו בהצלחה',
  successMessage: 'תודה רבה. אחזור אליכם בהקדם לתיאום פגישת ההיכרות.',
  steps: withBrandIntro([
    {
      id: 'household_type',
      type: 'single',
      title: 'מי גר בבית?',
      required: true,
      options: [
        { value: 'single', label: 'אדם אחד' },
        { value: 'couple', label: 'זוג' },
        { value: 'family', label: 'משפחה עם ילדים' },
        { value: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'children_ages',
      type: 'single',
      title: 'אם יש ילדים בבית, מה הגילאים?',
      options: [
        { value: 'none', label: 'אין' },
        { value: '1_6', label: '1-6' },
        { value: '6_12', label: '6-12' },
        { value: '12_18', label: '12-18' },
        { value: '18_plus', label: '18 ומעלה' },
      ],
      showWhen: { fieldId: 'household_type', equals: 'family' },
    },
    {
      id: 'property_type',
      type: 'single',
      title: 'סוג הנכס:',
      required: true,
      options: [
        { value: 'apartment', label: 'דירה' },
        { value: 'private_home', label: 'בית פרטי' },
        { value: 'penthouse', label: 'פנטהאוז' },
        { value: 'contractor_apartment', label: 'דירת קבלן' },
        { value: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'property_status',
      type: 'single',
      title: 'מה הסטטוס הנוכחי שלכם ושל הנכס?',
      required: true,
      options: [
        { value: 'before_purchase', label: 'לפני רכישה' },
        { value: 'purchased_before_renovation', label: 'נרכש , לפני שיפוץ' },
        { value: 'during_renovation', label: 'במהלך שיפוץ' },
        { value: 'living_and_planning', label: 'גרים בבית ורוצים לשפץ' },
        { value: 'moving_out_for_renovation', label: 'יוצאים מהבית לטובת שיפוץ' },
      ],
    },
    {
      id: 'renovation_scope',
      type: 'single',
      title: 'מה היקף השיפוץ המתוכנן?',
      required: true,
      options: [
        { value: 'styling_only', label: 'הום סטיילינג בלבד' },
        { value: 'cosmetic', label: 'שיפוץ קוסמטי' },
        { value: 'partial', label: 'שיפוץ חלקי' },
        { value: 'full', label: 'שיפוץ מלא' },
        { value: 'rebuild_structural', label: 'בנייה מחדש / שינוי מבני' },
      ],
    },
    {
      id: 'renovation_areas',
      type: 'multi',
      title: 'אילו אזורים כלולים בשיפוץ?',
      required: true,
      options: [
        { value: 'living_room', label: 'סלון' },
        { value: 'kitchen', label: 'מטבח' },
        { value: 'bedrooms', label: 'חדרי שינה' },
        { value: 'bathrooms', label: 'חדרי רחצה' },
        { value: 'toilets', label: 'שירותים' },
        { value: 'balcony_outdoor', label: 'מרפסת / חוץ' },
        { value: 'entire_home', label: 'כל הבית' },
      ],
    },
    {
      id: 'renovation_reason',
      type: 'single',
      title: 'מה הסיבה לשיפוץ?',
      options: [
        { value: 'design_upgrade', label: 'שדרוג עיצובי' },
        { value: 'functional_need', label: 'צורך פונקציונלי' },
        { value: 'new_home', label: 'מעבר לבית חדש' },
        { value: 'investment', label: 'השקעה/השכרה' },
        { value: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'residents_count',
      type: 'single',
      title: 'כמה אנשים יגורו בבית?',
      options: [
        { value: '1_2', label: '1–2' },
        { value: '3_4', label: '3–4' },
        { value: '5_plus', label: '5+' },
      ],
    },
    {
      id: 'has_children',
      type: 'single',
      title: 'האם יש ילדים?',
      options: [
        { value: 'yes', label: 'כן' },
        { value: 'infants', label: 'תינוקות' },
        { value: 'kindergarten', label: 'גן' },
        { value: 'school', label: 'בית ספר' },
        { value: 'teens', label: 'מתבגרים' },
        { value: 'no', label: 'לא' },
      ],
    },
    {
      id: 'pets',
      type: 'single',
      title: 'האם יש חיות מחמד?',
      options: [
        { value: 'yes', label: 'כן' },
        { value: 'no', label: 'לא' },
      ],
    },
    {
      id: 'current_pain',
      type: 'single',
      title: 'מה הכי מפריע לך בבית כיום?',
      options: [
        { value: 'layout', label: 'חלוקה לא נכונה' },
        { value: 'storage', label: 'חוסר אחסון' },
        { value: 'lighting', label: 'תאורה' },
        { value: 'flow', label: 'זרימה לא טובה' },
        { value: 'outdated_design', label: 'עיצוב מיושן' },
        { value: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'dream_home',
      type: 'single',
      title: 'מה החלום שלך לבית אחרי השיפוץ?',
      options: [
        { value: 'open_spacious', label: 'פתוח ומרווח' },
        { value: 'warm_family', label: 'חמים ומשפחתי' },
        { value: 'luxury_precise', label: 'יוקרתי ומדויק' },
        { value: 'functional_comfy', label: 'פונקציונלי ונוח' },
        { value: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'design_style',
      type: 'single',
      title: 'איזה סגנון הכי מדבר אליך?',
      options: [
        { value: 'modern', label: 'מודרני' },
        { value: 'warm_modern', label: 'מודרני חם' },
        { value: 'rural', label: 'כפרי' },
        { value: 'classic', label: 'קלאסי' },
        { value: 'minimal', label: 'מינימליסטי' },
        { value: 'open', label: 'לא יודעת / פתוח/ה להצעות' },
      ],
    },
    {
      id: 'structural_changes_importance',
      type: 'single',
      title: 'עד כמה חשוב לך שינוי מבני (שבירת קירות וכו’)?',
      options: [
        { value: 'very', label: 'מאוד חשוב' },
        { value: 'if_needed', label: 'אפשרי אם צריך' },
        { value: 'avoid', label: 'מעדיפ/ה להימנע' },
      ],
    },
    {
      id: 'has_arch_plan',
      type: 'single',
      title: 'האם יש תכנית אדריכלית קיימת?',
      options: [
        { value: 'yes', label: 'כן' },
        { value: 'no', label: 'לא' },
      ],
    },
    {
      id: 'worked_with_designer',
      type: 'single',
      title: 'האם עבדת עם מעצבת/אדריכל בעבר?',
      options: [
        { value: 'yes', label: 'כן' },
        { value: 'no', label: 'לא' },
      ],
    },
    {
      id: 'process_priority',
      type: 'single',
      title: 'מה הכי חשוב לך בתהליך?',
      options: [
        { value: 'design', label: 'עיצוב' },
        { value: 'functionality', label: 'פונקציונליות' },
        { value: 'full_support', label: 'ליווי מלא' },
        { value: 'time_saving', label: 'חיסכון בזמן' },
        { value: 'budget_control', label: 'שליטה בתקציב' },
      ],
    },
    {
      id: 'preserve_items',
      type: 'single',
      title: 'האם יש רהיטים/אלמנטים שחשוב לשמור?',
      options: [
        { value: 'yes', label: 'כן' },
        { value: 'no', label: 'לא' },
      ],
    },
    {
      id: 'preserve_items_note',
      type: 'longText',
      title: 'במידה וענית כן, אשמח שתצלם את הפריטים הללו עבור הפגישה שלנו.',
      placeholder: 'אפשר לציין אילו פריטים חשוב לשמור',
      showWhen: { fieldId: 'preserve_items', equals: 'yes' },
    },
    {
      id: 'renovation_budget',
      type: 'single',
      title:
        'מה התקציב שלכם לשיפוץ הבית? בואו נדבר דוגרי. עבודה לפי תקציב חיונית עבור הצלחת הפרויקט שלכם.',
      required: true,
      options: [
        {
          value: '200_300k',
          label:
            'בין 200-300 אלף שח (דירות בבניה / הום סטיילינג/ פחות לשיפוצים.)',
        },
        {
          value: '300_500k',
          label: 'בין 300-500 אלף שח (שיפוץ /דירה בבניה)',
        },
        { value: '500_750k', label: 'בין 500-750 אלף שח' },
        { value: '750_1m', label: 'בין 750-1M אלף שח' },
        { value: 'over_1m', label: 'מעל 1M מיליון שח' },
        { value: 'other', label: 'אחר:' },
      ],
    },
    {
      id: 'renovation_budget_other',
      type: 'text',
      title: 'נא לפרט',
      placeholder: 'תקציב או פירוט',
      required: true,
      showWhen: { fieldId: 'renovation_budget', equals: 'other' },
    },
    {
      id: 'involvement_level',
      type: 'single',
      title: 'מה תרצה/י שתהיה רמת המעורבות שלך בתהליך?',
      options: [
        { value: 'very_involved', label: 'רוצה להיות מעורבת מאוד' },
        { value: 'medium', label: 'בינונית' },
        { value: 'managed_for_me', label: 'מעדיפה שינהלו עבורי' },
      ],
    },
    {
      id: 'existing_contractors',
      type: 'single',
      title: 'האם יש קבלן/אנשי מקצוע שעבדת איתם שתרצה לשלב בפרוייקט?',
      options: [
        { value: 'yes', label: 'כן' },
        { value: 'no', label: 'לא' },
      ],
    },
    {
      id: 'timeline',
      type: 'single',
      title: 'מה לוחות הזמנים הרצויים?',
      options: [
        { value: 'immediate', label: 'מיידי' },
        { value: 'within_month', label: 'תוך חודש' },
        { value: '1_3_months', label: 'עוד 1–3 חודשים' },
      ],
    },
    {
      id: 'easy_maintenance',
      type: 'single',
      title: 'האם חשוב לך בית קל לתחזוקה?',
      options: [
        { value: 'very', label: 'מאוד' },
        { value: 'important', label: 'חשוב' },
        { value: 'less', label: 'פחות חשוב' },
      ],
    },
    {
      id: 'specific_materials',
      type: 'single',
      title: 'האם חשוב לך שימוש בחומרים מסוימים?',
      options: [
        { value: 'yes', label: 'כן (למשל: טבעיים / עמידים / יוקרתיים)' },
        { value: 'no', label: 'לא' },
      ],
    },
    {
      id: 'custom_storage',
      type: 'single',
      title: 'האם תרצה/י פתרונות אחסון מותאמים אישית?',
      options: [
        { value: 'yes', label: 'כן' },
        { value: 'no', label: 'לא' },
        { value: 'maybe', label: 'אולי' },
      ],
    },
    {
      id: 'hosting_frequency',
      type: 'single',
      title: 'כמה אתם מארחים בבית?',
      options: [
        { value: 'a_lot', label: 'הרבה' },
        { value: 'sometimes', label: 'לפעמים' },
        { value: 'rarely', label: 'כמעט ולא' },
      ],
    },
    {
      id: 'kitchen_is_central',
      type: 'single',
      title: 'האם המטבח הוא מרכזי בבית?',
      options: [
        { value: 'very', label: 'מאוד' },
        { value: 'medium', label: 'בינוני' },
        { value: 'no', label: 'לא' },
      ],
    },
    {
      id: 'kitchen_priority',
      type: 'single',
      title: 'מה חשוב לך במיוחד במטבח?',
      options: [
        { value: 'storage', label: 'אחסון' },
        { value: 'look', label: 'נראות' },
        { value: 'worktops', label: 'משטחי עבודה' },
        { value: 'island_seating', label: 'אי / ישיבה' },
        { value: 'all', label: 'שילוב הכל' },
      ],
    },
    {
      id: 'bathroom_priority',
      type: 'single',
      title: 'מה חשוב לך בחדרי רחצה?',
      options: [
        { value: 'design', label: 'עיצוב' },
        { value: 'functionality', label: 'פונקציונליות' },
        { value: 'spa', label: 'תחושת ספא' },
        { value: 'easy_maintenance', label: 'תחזוקה קלה' },
      ],
    },
    {
      id: 'home_feeling',
      type: 'single',
      title: 'מה הכי חשוב לך להרגיש בבית?',
      options: [
        { value: 'design_wow', label: 'וואו עיצובי' },
        { value: 'works_perfect', label: 'בית שעובד מושלם' },
        { value: 'both', label: 'שילוב של שניהם' },
        { value: 'pleasant_process', label: 'תהליך נעים וזורם' },
      ],
    },
    {
      id: 'extra_notes',
      type: 'longText',
      title: 'משהו נוסף שחשוב לך שאדע לפני הפגישה?',
      placeholder: 'כל מה שחשוב לך שאכיר מראש',
    },
    {
      id: 'full_name',
      type: 'text',
      title: 'שם מלא',
      required: true,
    },
    {
      id: 'phone',
      type: 'text',
      title: 'טלפון / וואטסאפ',
      required: true,
      placeholder: '05X-XXXXXXX',
    },
    {
      id: 'email',
      type: 'text',
      title: 'אימייל',
      placeholder: 'name@example.com',
    },
  ]),
};
